use tauri_plugin_sql::{Migration, MigrationKind};

/// 初始 schema。每条 Migration 仅含一条 SQL 语句（sqlx 单语句执行），
/// 全部使用 IF NOT EXISTS，安全可重入。
pub fn migrations() -> Vec<Migration> {
    vec![
        Migration {
            version: 1,
            description: "create_projects",
            sql: "CREATE TABLE IF NOT EXISTS projects (id TEXT PRIMARY KEY, name TEXT NOT NULL, color TEXT NOT NULL DEFAULT '#0078d4', keywords TEXT NOT NULL DEFAULT '[]', is_active INTEGER NOT NULL DEFAULT 1, sort_order INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL)",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 2,
            description: "create_tasks",
            sql: "CREATE TABLE IF NOT EXISTS tasks (id TEXT PRIMARY KEY, title TEXT NOT NULL, project_id TEXT, status TEXT NOT NULL DEFAULT 'active', start_date TEXT NOT NULL, end_date TEXT, note TEXT NOT NULL DEFAULT '', created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL)",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 3,
            description: "index_tasks_status",
            sql: "CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status)",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 4,
            description: "index_tasks_project",
            sql: "CREATE INDEX IF NOT EXISTS idx_tasks_project ON tasks(project_id)",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 5,
            description: "create_records",
            sql: "CREATE TABLE IF NOT EXISTS records (id TEXT PRIMARY KEY, task_id TEXT, project_id TEXT, content TEXT NOT NULL, duration_min INTEGER, day TEXT NOT NULL, half TEXT NOT NULL, source TEXT NOT NULL DEFAULT 'manual', created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, meta TEXT NOT NULL DEFAULT '{}', FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE SET NULL, FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE SET NULL)",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 6,
            description: "index_records_day_half",
            sql: "CREATE INDEX IF NOT EXISTS idx_records_day_half ON records(day, half)",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 7,
            description: "index_records_task",
            sql: "CREATE INDEX IF NOT EXISTS idx_records_task ON records(task_id)",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 8,
            description: "index_records_project",
            sql: "CREATE INDEX IF NOT EXISTS idx_records_project ON records(project_id)",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 9,
            description: "create_templates",
            sql: "CREATE TABLE IF NOT EXISTS templates (id TEXT PRIMARY KEY, name TEXT NOT NULL, body TEXT NOT NULL DEFAULT '', is_default INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL)",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 10,
            description: "create_reports",
            sql: "CREATE TABLE IF NOT EXISTS reports (id TEXT PRIMARY KEY, month TEXT NOT NULL, template_id TEXT, body TEXT NOT NULL DEFAULT '', provider TEXT NOT NULL DEFAULT '', model TEXT NOT NULL DEFAULT '', created_at INTEGER NOT NULL)",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 11,
            description: "index_reports_month",
            sql: "CREATE INDEX IF NOT EXISTS idx_reports_month ON reports(month)",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 12,
            description: "create_settings",
            sql: "CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL)",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 13,
            description: "reports_add_date_from",
            sql: "ALTER TABLE reports ADD COLUMN date_from TEXT",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 14,
            description: "reports_add_date_to",
            sql: "ALTER TABLE reports ADD COLUMN date_to TEXT",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 15,
            description: "records_add_run_id",
            sql: "ALTER TABLE records ADD COLUMN run_id TEXT",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 16,
            description: "index_records_run",
            sql: "CREATE INDEX IF NOT EXISTS idx_records_run ON records(run_id)",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 17,
            description: "create_collector_state",
            sql: "CREATE TABLE IF NOT EXISTS collector_state (provider TEXT NOT NULL, file TEXT NOT NULL, byte_offset INTEGER NOT NULL DEFAULT 0, updated_at INTEGER NOT NULL, PRIMARY KEY (provider, file))",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 18,
            description: "create_ingested_events",
            sql: "CREATE TABLE IF NOT EXISTS ingested_events (fingerprint TEXT PRIMARY KEY, provider TEXT NOT NULL, day TEXT NOT NULL, kind TEXT NOT NULL, payload TEXT NOT NULL DEFAULT '{}', created_at INTEGER NOT NULL)",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 19,
            description: "index_ingested_day",
            sql: "CREATE INDEX IF NOT EXISTS idx_ingested_day ON ingested_events(day)",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 20,
            description: "create_consolidate_runs",
            sql: "CREATE TABLE IF NOT EXISTS consolidate_runs (id TEXT PRIMARY KEY, day TEXT NOT NULL, input_sig TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'success', summary TEXT NOT NULL DEFAULT '', created_at INTEGER NOT NULL)",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 21,
            description: "index_runs_day",
            sql: "CREATE INDEX IF NOT EXISTS idx_runs_day ON consolidate_runs(day)",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 22,
            description: "tasks_add_source",
            sql: "ALTER TABLE tasks ADD COLUMN source TEXT NOT NULL DEFAULT 'manual'",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 23,
            description: "tasks_add_external_key",
            sql: "ALTER TABLE tasks ADD COLUMN external_key TEXT",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 24,
            description: "index_tasks_external_unique",
            sql: "CREATE UNIQUE INDEX IF NOT EXISTS idx_tasks_external_key ON tasks(external_key)",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 25,
            description: "create_choerodon_sync_log",
            sql: "CREATE TABLE IF NOT EXISTS choerodon_sync_log (log_id TEXT PRIMARY KEY, record_id TEXT NOT NULL, day TEXT NOT NULL, minutes INTEGER NOT NULL DEFAULT 0, strategy_run_id TEXT, payload TEXT NOT NULL DEFAULT '{}', created_at INTEGER NOT NULL)",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 26,
            description: "index_sync_log_record",
            sql: "CREATE INDEX IF NOT EXISTS idx_sync_log_record ON choerodon_sync_log(record_id)",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 27,
            description: "create_noise_reviews",
            sql: "CREATE TABLE IF NOT EXISTS noise_reviews (fingerprint TEXT PRIMARY KEY, workspace_id TEXT NOT NULL DEFAULT 'work', status TEXT NOT NULL, digest TEXT NOT NULL DEFAULT '', reason TEXT NOT NULL DEFAULT '', confidence REAL NOT NULL DEFAULT 0, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 28,
            description: "index_noise_ws_status",
            sql: "CREATE INDEX IF NOT EXISTS idx_noise_ws_status ON noise_reviews(workspace_id, status)",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 29,
            description: "create_workspaces",
            sql: "CREATE TABLE IF NOT EXISTS workspaces (id TEXT PRIMARY KEY, name TEXT NOT NULL, type TEXT NOT NULL DEFAULT 'work', is_default INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL)",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 30,
            description: "records_add_workspace",
            sql: "ALTER TABLE records ADD COLUMN workspace_id TEXT NOT NULL DEFAULT 'work'",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 31,
            description: "index_records_workspace",
            sql: "CREATE INDEX IF NOT EXISTS idx_records_workspace ON records(workspace_id)",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 32,
            description: "projects_add_workspace",
            sql: "ALTER TABLE projects ADD COLUMN workspace_id TEXT NOT NULL DEFAULT 'work'",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 33,
            description: "tasks_add_workspace",
            sql: "ALTER TABLE tasks ADD COLUMN workspace_id TEXT NOT NULL DEFAULT 'work'",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 34,
            description: "records_add_record_type",
            sql: "ALTER TABLE records ADD COLUMN record_type TEXT NOT NULL DEFAULT 'work'",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 35,
            description: "records_add_learnings",
            sql: "ALTER TABLE records ADD COLUMN learnings TEXT NOT NULL DEFAULT '[]'",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 36,
            description: "records_add_tags",
            sql: "ALTER TABLE records ADD COLUMN tags TEXT NOT NULL DEFAULT '[]'",
            kind: MigrationKind::Up,
        },
        Migration {
            version: 37,
            description: "create_retrospectives",
            sql: "CREATE TABLE IF NOT EXISTS retrospectives (id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL DEFAULT 'work', period TEXT NOT NULL, kind TEXT NOT NULL, content TEXT NOT NULL, created_at INTEGER NOT NULL)",
            kind: MigrationKind::Up,
        },
    ]
}
